/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package list2;

import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author My PC
 */
public class ListEx extends javax.swing.JFrame {

    /**
     * Creates new form ListEx
     */
    public ListEx() {
        initComponents();
        btnremove.setEnabled(false);
        btnremoven.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        l1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        l2 = new javax.swing.JList<>();
        btnadd1 = new javax.swing.JButton();
        btnaddn = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        btnremoven = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Danh sách môn thể thao");

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Môn yêu thích");

        l1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Bóng đá", "Bóng chuyền", "Bóng rổ", "Bơi lội", "Chạy" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(l1);

        jScrollPane2.setViewportView(l2);

        btnadd1.setText(">");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        btnaddn.setText(">>");
        btnaddn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnActionPerformed(evt);
            }
        });

        btnremove.setText("<");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        btnremoven.setText("<<");
        btnremoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremovenActionPerformed(evt);
            }
        });

        btnadd.setText("+");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnaddn)
                            .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnremoven)
                            .addComponent(btnadd1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnadd1)
                        .addGap(18, 18, 18)
                        .addComponent(btnaddn)
                        .addGap(18, 18, 18)
                        .addComponent(btnremove)
                        .addGap(18, 18, 18)
                        .addComponent(btnremoven)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     static public void AddtoList(String s)
    {
        /*ListModel DS = l1.getModel();
        DefaultListModel List;
        List = new DefaultListModel();
        for (int i=0; i<DS.getSize(); i++)
            {
                List.addElement(DS.getElementAt(i).toString());
            }
        List.addElement(s);
        l1.setModel(List);*/
    }
    
    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:
        if (l1.isSelectionEmpty() == false)
        {
            ListModel DS = l1.getModel();
            ListModel DSL2 = l2.getModel();
            DefaultListModel List;
            List = new DefaultListModel();
            for (int i=0; i<DS.getSize(); i++)
            {   
                if (DS.getElementAt(i).toString() == l1.getSelectedValue().toString())
                    List.addElement(DS.getElementAt(i).toString());
            }
            for (int i=0; i<DSL2.getSize(); i++)
            {
                List.addElement(DSL2.getElementAt(i).toString());
            }
            l2.setModel(List);
            
            ListModel DS2 = l1.getModel();        
            DefaultListModel List2;
            List2 = new DefaultListModel();
            for (int i=0; i<DS2.getSize(); i++)
            {   
                if (DS2.getElementAt(i).toString() != l1.getSelectedValue().toString())
                    List2.addElement(DS2.getElementAt(i).toString());
            }
            l1.setModel(List2);
            
            if (l1.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(false);
                btnaddn.setEnabled(false);
                btnremove.setEnabled(true);
                btnremoven.setEnabled(true);
            }
            if (l2.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(true);
                btnaddn.setEnabled(true);
                btnremove.setEnabled(false);
                btnremoven.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnadd1ActionPerformed

    private void btnaddnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnActionPerformed
        // TODO add your handling code here:
            ListModel DS = l1.getModel();        
            DefaultListModel List;
            List = new DefaultListModel();
            for (int i=0; i<DS.getSize(); i++)
            {   
                List.addElement(DS.getElementAt(i).toString());
            }
            l2.setModel(List);
                
            DefaultListModel List2;
            List2 = new DefaultListModel();
            l1.setModel(List2);
            
            if (l1.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(false);
                btnaddn.setEnabled(false);
            }
            if (l1.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(false);
                btnaddn.setEnabled(false);
                btnremove.setEnabled(true);
                btnremoven.setEnabled(true);
            }
            if (l2.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(true);
                btnaddn.setEnabled(true);
                btnremove.setEnabled(false);
                btnremoven.setEnabled(false);
            }
    }//GEN-LAST:event_btnaddnActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // TODO add your handling code here:
        if (l2.isSelectionEmpty() == false)
        {
            ListModel DS = l2.getModel();
            ListModel DSL2 = l1.getModel();
            DefaultListModel List;
            List = new DefaultListModel();
            for (int i=0; i<DS.getSize(); i++)
            {   
                if (DS.getElementAt(i).toString() == l2.getSelectedValue().toString())
                    List.addElement(DS.getElementAt(i).toString());
            }
            for (int i=0; i<DSL2.getSize(); i++)
            {
                List.addElement(DSL2.getElementAt(i).toString());
            }
            l1.setModel(List);
            
            ListModel DS2 = l2.getModel();        
            DefaultListModel List2;
            List2 = new DefaultListModel();
            for (int i=0; i<DS2.getSize(); i++)
            {   
                if (DS2.getElementAt(i).toString() != l2.getSelectedValue().toString())
                    List2.addElement(DS2.getElementAt(i).toString());
            }
            l2.setModel(List2);
            
            if (l1.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(false);
                btnaddn.setEnabled(false);
                btnremove.setEnabled(true);
                btnremoven.setEnabled(true);
            }
            if (l2.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(true);
                btnaddn.setEnabled(true);
                btnremove.setEnabled(false);
                btnremoven.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnremovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremovenActionPerformed
        // TODO add your handling code here:
            ListModel DS = l2.getModel();        
            DefaultListModel List;
            List = new DefaultListModel();
            for (int i=0; i<DS.getSize(); i++)
            {   
                List.addElement(DS.getElementAt(i).toString());
            }
            l1.setModel(List);
                
            DefaultListModel List2;
            List2 = new DefaultListModel();
            l2.setModel(List2);
            
            if (l1.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(false);
                btnaddn.setEnabled(false);
                btnremove.setEnabled(true);
                btnremoven.setEnabled(true);
            }
            if (l2.getModel().getSize() == 0)
            {
                btnadd1.setEnabled(true);
                btnaddn.setEnabled(true);
                btnremove.setEnabled(false);
                btnremoven.setEnabled(false);
            }
    }//GEN-LAST:event_btnremovenActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        /*Add frm = new Add();
        frm.setVisible(true);*/     
        
        String s = JOptionPane.showInputDialog(this,"Input sport below");
       
        
        ListModel DS = l1.getModel();
        DefaultListModel List;
        List = new DefaultListModel();
        for (int i=0; i<DS.getSize(); i++)
            {
                List.addElement(DS.getElementAt(i).toString());
            }
        List.addElement(s);
        l1.setModel(List);
    }//GEN-LAST:event_btnaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btnaddn;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnremoven;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> l1;
    private javax.swing.JList<String> l2;
    // End of variables declaration//GEN-END:variables
}
