/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        TableNV.setModel(BLL.NhanVienModel());
        TableKH.setModel(BLL.KhachModel());
        TableHang.setModel(BLL.HangModel());
        TableHD.setModel(BLL.HDBanModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        G1 = new javax.swing.ButtonGroup();
        Tab = new javax.swing.JTabbedPane();
        PN1 = new javax.swing.JPanel();
        SP1 = new javax.swing.JScrollPane();
        TableNV = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        RBNam = new javax.swing.JRadioButton();
        RBNu = new javax.swing.JRadioButton();
        txtmanv = new javax.swing.JTextField();
        txttennv = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        PN2 = new javax.swing.JPanel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        SP2 = new javax.swing.JScrollPane();
        TableKH = new javax.swing.JTable();
        txtmakh = new javax.swing.JTextField();
        txttenkh = new javax.swing.JTextField();
        txtdiachikh = new javax.swing.JTextField();
        txtsdtkh = new javax.swing.JTextField();
        btnthem2 = new javax.swing.JButton();
        btnsua2 = new javax.swing.JButton();
        btnxoa2 = new javax.swing.JButton();
        PN3 = new javax.swing.JPanel();
        SP3 = new javax.swing.JScrollPane();
        TableHang = new javax.swing.JTable();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        lb12 = new javax.swing.JLabel();
        lb13 = new javax.swing.JLabel();
        lb14 = new javax.swing.JLabel();
        lb15 = new javax.swing.JLabel();
        txtmahang = new javax.swing.JTextField();
        txttenhang = new javax.swing.JTextField();
        txtghichu = new javax.swing.JTextField();
        txtsoluong = new javax.swing.JTextField();
        txtdongianhap = new javax.swing.JTextField();
        txtdongiaban = new javax.swing.JTextField();
        btnthem3 = new javax.swing.JButton();
        btnsua3 = new javax.swing.JButton();
        btnxoa3 = new javax.swing.JButton();
        PN4 = new javax.swing.JPanel();
        SP4 = new javax.swing.JScrollPane();
        TableHD = new javax.swing.JTable();
        lb16 = new javax.swing.JLabel();
        lb17 = new javax.swing.JLabel();
        lb18 = new javax.swing.JLabel();
        lb19 = new javax.swing.JLabel();
        lb20 = new javax.swing.JLabel();
        txtmahd = new javax.swing.JTextField();
        txtmanvhd = new javax.swing.JTextField();
        txttongtien = new javax.swing.JTextField();
        txtngayban = new javax.swing.JTextField();
        txtmakhachhd = new javax.swing.JTextField();
        btnthem4 = new javax.swing.JButton();
        btnsua4 = new javax.swing.JButton();
        btnxoa4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNVMouseClicked(evt);
            }
        });
        SP1.setViewportView(TableNV);

        btnthem.setForeground(new java.awt.Color(255, 0, 51));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setForeground(new java.awt.Color(255, 0, 51));
        btnsua.setText("Sửa");
        btnsua.setPreferredSize(new java.awt.Dimension(62, 32));
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setForeground(new java.awt.Color(255, 0, 51));
        btnxoa.setText("Xóa");
        btnxoa.setPreferredSize(new java.awt.Dimension(62, 32));
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        lb1.setForeground(new java.awt.Color(0, 51, 204));
        lb1.setText("Mã NV");

        lb2.setForeground(new java.awt.Color(0, 51, 204));
        lb2.setText("Tên NV");

        lb3.setForeground(new java.awt.Color(0, 51, 204));
        lb3.setText("Địa chỉ");

        lb4.setForeground(new java.awt.Color(0, 51, 204));
        lb4.setText("SDT");

        lb5.setForeground(new java.awt.Color(0, 51, 204));
        lb5.setText("Ngày sinh");

        G1.add(RBNam);
        RBNam.setForeground(new java.awt.Color(0, 51, 204));
        RBNam.setText("Nam");

        G1.add(RBNu);
        RBNu.setForeground(new java.awt.Color(0, 51, 204));
        RBNu.setText("Nữ");

        javax.swing.GroupLayout PN1Layout = new javax.swing.GroupLayout(PN1);
        PN1.setLayout(PN1Layout);
        PN1Layout.setHorizontalGroup(
            PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SP1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PN1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb1)
                    .addComponent(lb3)
                    .addComponent(lb2))
                .addGap(18, 18, 18)
                .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN1Layout.createSequentialGroup()
                        .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RBNu)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PN1Layout.createSequentialGroup()
                        .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PN1Layout.createSequentialGroup()
                                .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(lb4)
                                .addGap(36, 36, 36)
                                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PN1Layout.createSequentialGroup()
                                .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(lb5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PN1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnthem)
                .addGap(18, 18, 18)
                .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PN1Layout.setVerticalGroup(
            PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN1Layout.createSequentialGroup()
                .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb1)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb4)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2)
                    .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb5)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb3)
                    .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RBNam)
                        .addComponent(RBNu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(PN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SP1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Tab.addTab("Nhân Viên", PN1);

        lb6.setForeground(new java.awt.Color(0, 51, 204));
        lb6.setText("Mã khách");

        lb7.setForeground(new java.awt.Color(0, 51, 204));
        lb7.setText("Tên khách");

        lb8.setForeground(new java.awt.Color(0, 51, 204));
        lb8.setText("Địa chỉ");

        lb9.setForeground(new java.awt.Color(0, 51, 204));
        lb9.setText("Điện thoại");

        TableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKHMouseClicked(evt);
            }
        });
        SP2.setViewportView(TableKH);

        btnthem2.setForeground(new java.awt.Color(255, 0, 51));
        btnthem2.setText("Thêm");
        btnthem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem2ActionPerformed(evt);
            }
        });

        btnsua2.setForeground(new java.awt.Color(255, 0, 51));
        btnsua2.setText("Sửa");
        btnsua2.setPreferredSize(new java.awt.Dimension(62, 32));
        btnsua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsua2ActionPerformed(evt);
            }
        });

        btnxoa2.setForeground(new java.awt.Color(255, 0, 51));
        btnxoa2.setText("Xóa");
        btnxoa2.setPreferredSize(new java.awt.Dimension(62, 32));
        btnxoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoa2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PN2Layout = new javax.swing.GroupLayout(PN2);
        PN2.setLayout(PN2Layout);
        PN2Layout.setHorizontalGroup(
            PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN2Layout.createSequentialGroup()
                .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SP2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                    .addGroup(PN2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PN2Layout.createSequentialGroup()
                                .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb7)
                                    .addComponent(lb6))
                                .addGap(18, 18, 18)
                                .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PN2Layout.createSequentialGroup()
                                    .addComponent(btnthem2)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnsua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnxoa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PN2Layout.createSequentialGroup()
                                    .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PN2Layout.createSequentialGroup()
                                            .addComponent(lb8)
                                            .addGap(18, 18, 18))
                                        .addComponent(lb9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PN2Layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(txtdiachikh, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PN2Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txtsdtkh, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PN2Layout.setVerticalGroup(
            PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb6)
                    .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb7)
                    .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb8)
                    .addComponent(txtdiachikh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsdtkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb9))
                .addGap(11, 11, 11)
                .addGroup(PN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem2)
                    .addComponent(btnsua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SP2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab("Khách Hàng", PN2);

        TableHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHangMouseClicked(evt);
            }
        });
        SP3.setViewportView(TableHang);

        lb10.setForeground(new java.awt.Color(0, 51, 204));
        lb10.setText("Mã hàng");

        lb11.setForeground(new java.awt.Color(0, 51, 204));
        lb11.setText("Tên hàng");

        lb12.setForeground(new java.awt.Color(0, 51, 204));
        lb12.setText("Số lượng");

        lb13.setForeground(new java.awt.Color(0, 51, 204));
        lb13.setText("Đơn giá nhập");

        lb14.setForeground(new java.awt.Color(0, 51, 204));
        lb14.setText("Đơn giá bán");

        lb15.setForeground(new java.awt.Color(0, 51, 204));
        lb15.setText("Ghi chú");

        btnthem3.setForeground(new java.awt.Color(255, 0, 51));
        btnthem3.setText("Thêm");
        btnthem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem3ActionPerformed(evt);
            }
        });

        btnsua3.setForeground(new java.awt.Color(255, 0, 51));
        btnsua3.setText("Sửa");
        btnsua3.setPreferredSize(new java.awt.Dimension(62, 32));
        btnsua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsua3ActionPerformed(evt);
            }
        });

        btnxoa3.setForeground(new java.awt.Color(255, 0, 51));
        btnxoa3.setText("Xóa");
        btnxoa3.setPreferredSize(new java.awt.Dimension(62, 32));
        btnxoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoa3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PN3Layout = new javax.swing.GroupLayout(PN3);
        PN3.setLayout(PN3Layout);
        PN3Layout.setHorizontalGroup(
            PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SP3, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE))
            .addGroup(PN3Layout.createSequentialGroup()
                .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN3Layout.createSequentialGroup()
                                .addComponent(lb15)
                                .addGap(18, 18, 18)
                                .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PN3Layout.createSequentialGroup()
                                .addComponent(lb11)
                                .addGap(18, 18, 18)
                                .addComponent(txttenhang, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PN3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lb10)
                        .addGap(18, 18, 18)
                        .addComponent(txtmahang, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb14)
                    .addComponent(lb12)
                    .addComponent(lb13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdongiaban, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdongianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(PN3Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnthem3)
                .addGap(18, 18, 18)
                .addComponent(btnsua3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnxoa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PN3Layout.setVerticalGroup(
            PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN3Layout.createSequentialGroup()
                        .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb10)
                                .addComponent(txtmahang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtsoluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb11)
                            .addComponent(txttenhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb13)
                            .addComponent(txtdongianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb14)
                            .addComponent(txtdongiaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb15)
                            .addComponent(txtghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb12))
                .addGap(18, 18, 18)
                .addGroup(PN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem3)
                    .addComponent(btnsua3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SP3, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab("Hàng", PN3);

        TableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHDMouseClicked(evt);
            }
        });
        SP4.setViewportView(TableHD);

        lb16.setForeground(new java.awt.Color(0, 51, 204));
        lb16.setText("Mã hóa đơn");

        lb17.setForeground(new java.awt.Color(0, 51, 204));
        lb17.setText("Mã nhân viên");

        lb18.setForeground(new java.awt.Color(0, 51, 204));
        lb18.setText("Ngày bán");

        lb19.setForeground(new java.awt.Color(0, 51, 204));
        lb19.setText("Mã khách");

        lb20.setForeground(new java.awt.Color(0, 51, 204));
        lb20.setText("Tổng tiền");

        btnthem4.setForeground(new java.awt.Color(255, 0, 51));
        btnthem4.setText("Thêm");
        btnthem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem4ActionPerformed(evt);
            }
        });

        btnsua4.setForeground(new java.awt.Color(255, 0, 51));
        btnsua4.setText("Sửa");
        btnsua4.setPreferredSize(new java.awt.Dimension(62, 32));
        btnsua4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsua4ActionPerformed(evt);
            }
        });

        btnxoa4.setForeground(new java.awt.Color(255, 0, 51));
        btnxoa4.setText("Xóa");
        btnxoa4.setPreferredSize(new java.awt.Dimension(62, 32));
        btnxoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PN4Layout = new javax.swing.GroupLayout(PN4);
        PN4.setLayout(PN4Layout);
        PN4Layout.setHorizontalGroup(
            PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PN4Layout.createSequentialGroup()
                .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SP4, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                    .addGroup(PN4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb17)
                            .addComponent(lb20)
                            .addComponent(lb16))
                        .addGap(18, 18, 18)
                        .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PN4Layout.createSequentialGroup()
                                .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmahd, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(txtmanvhd))
                                .addGap(18, 18, 18)
                                .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb19)
                                    .addComponent(lb18))
                                .addGap(10, 10, 10)
                                .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmakhachhd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtngayban, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PN4Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnthem4)
                .addGap(18, 18, 18)
                .addComponent(btnsua4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnxoa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PN4Layout.setVerticalGroup(
            PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PN4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb16)
                        .addComponent(txtmahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PN4Layout.createSequentialGroup()
                        .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtngayban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb18))
                        .addGap(18, 18, 18)
                        .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb19)
                            .addComponent(txtmakhachhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmanvhd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb17))))
                .addGap(24, 24, 24)
                .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb20)
                    .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem4)
                    .addComponent(btnsua4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SP4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tab.addTab("Hóa Đơn", PN4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tab)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnxoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoa4ActionPerformed
        // TODO add your handling code here:
        int n = TableHD.getSelectedRow();
        String MaHD = BLL.HDBanModel().getValueAt(n, 0).toString();
        BLL.DeleteHDBan(MaHD);
        TableHD.setModel(BLL.HDBanModel());
    }//GEN-LAST:event_btnxoa4ActionPerformed

    private void btnsua4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsua4ActionPerformed
        // TODO add your handling code here:
        BLL.UpdateHDBan(txtmahd.getText(),txtmanvhd.getText(),txtngayban.getText(),txtmakhachhd.getText(),Float.valueOf(txttongtien.getText()));
        TableHD.setModel(BLL.HDBanModel());
    }//GEN-LAST:event_btnsua4ActionPerformed

    private void btnthem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem4ActionPerformed
        // TODO add your handling code here:
        BLL.InsertHDBan(txtmahd.getText(),txtmanvhd.getText(),txtngayban.getText(),txtmakhachhd.getText(),Float.valueOf(txttongtien.getText()));
        TableHD.setModel(BLL.HDBanModel());
    }//GEN-LAST:event_btnthem4ActionPerformed

    private void TableHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHDMouseClicked
        // TODO add your handling code here:
        int n = TableHD.getSelectedRow();
        txtmahd.setText(BLL.HDBanModel().getValueAt(n, 0).toString());
        txtmanvhd.setText(BLL.HDBanModel().getValueAt(n, 1).toString());
        txtngayban.setText(BLL.HDBanModel().getValueAt(n, 2).toString());
        txtmakhachhd.setText(BLL.HDBanModel().getValueAt(n, 3).toString());
        txttongtien.setText(BLL.HDBanModel().getValueAt(n, 4).toString());
    }//GEN-LAST:event_TableHDMouseClicked

    private void btnxoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoa3ActionPerformed
        // TODO add your handling code here:
        int n = TableHang.getSelectedRow();
        String MaHang = BLL.HangModel().getValueAt(n, 0).toString();
        BLL.DeleteHang(MaHang);
        TableHang.setModel(BLL.HangModel());
    }//GEN-LAST:event_btnxoa3ActionPerformed

    private void btnsua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsua3ActionPerformed
        // TODO add your handling code here:
        BLL.UpdateHang(txtmahang.getText(),txttenhang.getText(),Float.valueOf(txtsoluong.getText()),Float.valueOf(txtdongianhap.getText()),Float.valueOf(txtdongiaban.getText()),txtghichu.getText());
        TableHang.setModel(BLL.HangModel());
    }//GEN-LAST:event_btnsua3ActionPerformed

    private void btnthem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem3ActionPerformed
        // TODO add your handling code here:
        BLL.InsertHang(txtmahang.getText(),txttenhang.getText(),Float.valueOf(txtsoluong.getText()),Float.valueOf(txtdongianhap.getText()),Float.valueOf(txtdongiaban.getText()),txtghichu.getText());
        TableHang.setModel(BLL.HangModel());
    }//GEN-LAST:event_btnthem3ActionPerformed

    private void TableHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHangMouseClicked
        // TODO add your handling code here:
        int n = TableHang.getSelectedRow();
        txtmahang.setText(BLL.HangModel().getValueAt(n, 0).toString());
        txttenhang.setText(BLL.HangModel().getValueAt(n, 1).toString());
        txtsoluong.setText(BLL.HangModel().getValueAt(n, 2).toString());
        txtdongianhap.setText(BLL.HangModel().getValueAt(n, 3).toString());
        txtdongiaban.setText(BLL.HangModel().getValueAt(n, 4).toString());
        txtghichu.setText(BLL.HangModel().getValueAt(n, 5).toString());
    }//GEN-LAST:event_TableHangMouseClicked

    private void btnxoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoa2ActionPerformed
        // TODO add your handling code here:
        int n = TableKH.getSelectedRow();
        String MaKH = BLL.KhachModel().getValueAt(n, 0).toString();
        BLL.DeleteKhach(MaKH);
        TableKH.setModel(BLL.KhachModel());
    }//GEN-LAST:event_btnxoa2ActionPerformed

    private void btnsua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsua2ActionPerformed
        // TODO add your handling code here:
        BLL.UpdateKhach(txtmakh.getText(), txttenkh.getText(), txtdiachikh.getText(), txtsdtkh.getText());
        TableKH.setModel(BLL.KhachModel());
    }//GEN-LAST:event_btnsua2ActionPerformed

    private void btnthem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem2ActionPerformed
        // TODO add your handling code here:
        BLL.InsertKhach(txtmakh.getText(), txttenkh.getText(), txtdiachikh.getText(), txtsdtkh.getText());
        TableKH.setModel(BLL.KhachModel());
    }//GEN-LAST:event_btnthem2ActionPerformed

    private void TableKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKHMouseClicked
        // TODO add your handling code here:
        int n = TableKH.getSelectedRow();
        txtmakh.setText(BLL.KhachModel().getValueAt(n, 0).toString());
        txttenkh.setText(BLL.KhachModel().getValueAt(n, 1).toString());
        txtdiachikh.setText(BLL.KhachModel().getValueAt(n, 2).toString());
        txtsdtkh.setText(BLL.KhachModel().getValueAt(n, 3).toString());
    }//GEN-LAST:event_TableKHMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int n = TableNV.getSelectedRow();
        String MaNV = BLL.NhanVienModel().getValueAt(n, 0).toString();
        BLL.DeleteNhanVien(MaNV);
        TableNV.setModel(BLL.NhanVienModel());
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        String GioiTinh = null;
        if(RBNam.isSelected()){
            GioiTinh = "Nam";
        } else if(RBNu.isSelected()) {
            GioiTinh = "Nu";
        } else {
            JOptionPane.showMessageDialog(rootPane, "Giới tính thứ 3 chăng ?");
        }
        BLL.UpdateNhanVien(txtmanv.getText(), txttennv.getText(), GioiTinh, txtdiachi.getText(), txtsdt.getText(), txtngaysinh.getText());
        TableNV.setModel(BLL.NhanVienModel());
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        String GioiTinh = null;
        if(RBNam.isSelected()){
            GioiTinh = "Nam";
        } else if(RBNu.isSelected()) {
            GioiTinh = "Nu";
        } else {
            JOptionPane.showMessageDialog(rootPane, "Giới tính thứ 3 chăng ?");
        }
        BLL.InsertNhanVien(txtmanv.getText(), txttennv.getText(), GioiTinh, txtdiachi.getText(), txtsdt.getText(), txtngaysinh.getText());
        TableNV.setModel(BLL.NhanVienModel());
    }//GEN-LAST:event_btnthemActionPerformed

    private void TableNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNVMouseClicked
        // TODO add your handling code here:
        int n = TableNV.getSelectedRow();
        txtmanv.setText(BLL.NhanVienModel().getValueAt(n, 0).toString());
        txttennv.setText(BLL.NhanVienModel().getValueAt(n, 1).toString());
        txtdiachi.setText(BLL.NhanVienModel().getValueAt(n, 3).toString());
        txtsdt.setText(BLL.NhanVienModel().getValueAt(n, 4).toString());
        txtngaysinh.setText(BLL.NhanVienModel().getValueAt(n, 5).toString());
    }//GEN-LAST:event_TableNVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup G1;
    private javax.swing.JPanel PN1;
    private javax.swing.JPanel PN2;
    private javax.swing.JPanel PN3;
    private javax.swing.JPanel PN4;
    private javax.swing.JRadioButton RBNam;
    private javax.swing.JRadioButton RBNu;
    private javax.swing.JScrollPane SP1;
    private javax.swing.JScrollPane SP2;
    private javax.swing.JScrollPane SP3;
    private javax.swing.JScrollPane SP4;
    private javax.swing.JTabbedPane Tab;
    private javax.swing.JTable TableHD;
    private javax.swing.JTable TableHang;
    private javax.swing.JTable TableKH;
    private javax.swing.JTable TableNV;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnsua2;
    private javax.swing.JButton btnsua3;
    private javax.swing.JButton btnsua4;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthem2;
    private javax.swing.JButton btnthem3;
    private javax.swing.JButton btnthem4;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxoa2;
    private javax.swing.JButton btnxoa3;
    private javax.swing.JButton btnxoa4;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb13;
    private javax.swing.JLabel lb14;
    private javax.swing.JLabel lb15;
    private javax.swing.JLabel lb16;
    private javax.swing.JLabel lb17;
    private javax.swing.JLabel lb18;
    private javax.swing.JLabel lb19;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb20;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtdiachikh;
    private javax.swing.JTextField txtdongiaban;
    private javax.swing.JTextField txtdongianhap;
    private javax.swing.JTextField txtghichu;
    private javax.swing.JTextField txtmahang;
    private javax.swing.JTextField txtmahd;
    private javax.swing.JTextField txtmakh;
    private javax.swing.JTextField txtmakhachhd;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtmanvhd;
    private javax.swing.JTextField txtngayban;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtsdtkh;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttenhang;
    private javax.swing.JTextField txttenkh;
    private javax.swing.JTextField txttennv;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables
}
